version: '3.8'

services:
  # API App
  chat-api:
    image: node:20.13.1
    command: >
      bash -c "
        cd app &&
        npm install &&
        npm install -g typescript &&
        chmod +x migration-helper.sh &&
        sleep ${MIGRATION_DELAY_SECONDS} &&
        ./migration-helper.sh &&
        npm run build &&
        npm run preview
      "
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_MAIN_DB}
    env_file:
      .env
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./src:/app/src
      - ./:/app
    depends_on:
      - chat-db
      - chat-vector-db
      - chat-cache

  # database
  chat-db:
    image: postgres:14.12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_MAIN_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data:z

  chat-vector-db:
    image: qdrant/qdrant:v1.9.4
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"

  chat-cache:
    image: redis:7.2.4
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    # Runs on 6379 Docker
    volumes:
      - ./redisdata:/data:z
